# Generated by Django 4.1.3 on 2022-11-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='owner',
        ),
    ]
