# Generated by Django 4.1.2 on 2022-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userdata_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='radio',
            field=models.CharField(default='', max_length=10),
        ),
    ]
