# Generated by Django 4.1.2 on 2022-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userdata_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reportcard',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='reportcardcount',
            field=models.IntegerField(default=0),
        ),
    ]
