# Generated by Django 4.1.2 on 2022-11-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userdata_reportcard_userdata_reportcardcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='middlename',
        ),
        migrations.AddField(
            model_name='userdata',
            name='birth_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mob_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mother_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
