# Generated by Django 4.1.2 on 2022-11-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_userdata_firstname_remove_userdata_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='universities_applied',
            field=models.CharField(default='', max_length=50),
        ),
    ]
