# Generated by Django 4.1.2 on 2022-11-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_userdata_mob_no_alter_userdata_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
