# Generated by Django 4.1.2 on 2022-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_userdata_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
