# Generated by Django 4.1.2 on 2022-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_userdata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='reportcard',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='markscard',
            field=models.CharField(max_length=50),
        ),
    ]
