# Generated by Django 4.1.2 on 2022-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_userdata_reportcard_alter_userdata_markscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
    ]
