# Generated by Django 4.1.2 on 2022-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_userdata_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
