# Generated by Django 4.1.4 on 2022-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_userdata_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='verified',
            new_name='Cambridge_verified',
        ),
        migrations.AddField(
            model_name='userdata',
            name='Harward_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='MIT_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Oxford_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Stanford_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='UCLA_verified',
            field=models.BooleanField(default=False),
        ),
    ]
