# Generated by Django 4.1.5 on 2023-01-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_verified_userdata_cambridge_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='reportcardcount',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='universities_applied',
        ),
    ]
